### ISSUE TITLE
你好，想运行你的demo 选择视频后报下面这个错

### ISSUE THREAD

**Issue by Destroyer716** [galis/OpenTikTok#1]
2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: SLGLUtil#Could not compile vertex shader:
    	0:2: P0005: #version must be on the first line in a program and only whitespace are allowed in the declaration
    	
2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: SLGLUtil#Could not compile fragment shader:
    	0:2: P0005: #version must be on the first line in a program and only whitespace are allowed in the declaration
    	
2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: compileShader error!!
2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: SLGLUtil#Could not compile vertex shader:
    	0:2: P0005: #version must be on the first line in a program and only whitespace are allowed in the declaration
    	
2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: SLGLUtil#Could not compile fragment shader:
    	0:2: P0005: #version must be on the first line in a program and only whitespace are allowed in the declaration
    	
2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: compileShader error!!

**Comment by galis** [comment]
你好，请问可以说下手机型号以及系统版本号吗？

**Comment by galis** [comment]
> 2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: SLGLUtil#Could not compile vertex shader: 0:2: P0005: #version must be on the first line in a program and only whitespace are allowed in the declaration
> 
> 2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: SLGLUtil#Could not compile fragment shader: 0:2: P0005: #version must be on the first line in a program and only whitespace are allowed in the declaration
> 
> 2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: compileShader error!! 2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: SLGLUtil#Could not compile vertex shader: 0:2: P0005: #version must be on the first line in a program and only whitespace are allowed in the declaration
> 
> 2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: SLGLUtil#Could not compile fragment shader: 0:2: P0005: #version must be on the first line in a program and only whitespace are allowed in the declaration
> 
> 2022-03-02 14:41:59.670 5261-5385/com.galix.opentiktok E/SLMEDIA: compileShader error!!

你好，请问可以说下手机型号以及系统版本号吗？

**Comment by Destroyer716** [comment]
Redmi Note 10 pro  
android 11

**Comment by galis** [comment]
> 

你好，这个问题已经解决。原因是glsl脚本#version开头有个\n符号。

**Comment by galis** [comment]
> 你好，这个问题已经解决。原因是glsl脚本#version开头有个\n符号。



> Redmi Note 10 pro android 11

你好，这个问题已经解决。原因是glsl脚本#version开头有个\n符号。

**Comment by Destroyer716** [comment]
ok,谢谢
