### ISSUE TITLE
选中视频进入到编辑界面，视频不显示

### ISSUE THREAD

**Issue by Yanqilong** [galis/OpenTikTok#3]
机型：Oppo Reno5 5G
Android OS: 11

点击开始创作按钮后打开文件选择器，选中视频去到视频编辑页面，但是页面是黑色的视频没有加载成功，我把截图贴上来了
<img width="210" alt="image" src="https://user-images.githubusercontent.com/19600368/161437999-dd5eb2b5-19b6-4b6c-9a66-2ad60ddba8b1.png">

**Comment by galis** [comment]
再试试？新版本应该可以了。
