### ISSUE TITLE
导出失败

### ISSUE THREAD

**Issue by Alexanderser** [galis/OpenTikTok#6]
MediaCodec$CodecException: Error 0xfffffff3.

**Comment by galis** [comment]
麻烦说下：
手机型号+版本+视频信息+详细log.

**Comment by Alexanderser** [comment]
1,已解决:一加7p ,版本11  ,   MP4composite这个类中mediaFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);需要修改成这个参数
2,另外拼接视频导出时,转场这块似乎还有bug,无法直接导出,必须点中间那个拼接按钮设置转场动画才能成功导出,
3,能加个好友,探讨一下其他音视频相关的思路吗?因为用了您的这个框架,需要您指点一下

**Comment by galis** [comment]
> 1,已解决:一加7p ,版本11 , MP4composite这个类中mediaFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);需要修改成这个参数 2,另外拼接视频导出时,转场这块似乎还有bug,无法直接导出,必须点中间那个拼接按钮设置转场动画才能成功导出, 3,能加个好友,探讨一下其他音视频相关的思路吗?因为用了您的这个框架,需要您指点一下

我主页有联系方式，欢迎交流。
